# such config, much build...
dist: bionic
# we are not using `language: rust` here as travis does not support bionic for rust builds yet
language: minimal
install:
  # tmux version should be >=2.6
  - tmux -V
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain=stable --default-host=x86_64-unknown-linux-gnu -y
  - source $HOME/.cargo/env
  - rustup toolchain install nightly
  - nvm install 10
  - ./scripts/prepare-end2end-tests.sh
env:
  - RUST_CHAIN=stable
  - RUST_CHAIN=nightly
script:
  - ./scripts/ci-build.sh
# do not use deploy here as deploy scripts are not executed for failed builds
after_script:
  - >
    test "$TRAVIS_PULL_REQUEST" == false && \
    test "$TRAVIS_BRANCH" == master && \
    GITHUB_REPO_SLUG="$TRAVIS_REPO_SLUG" ./scripts/deploy-badges.sh
# It was time for Thomas to leave. He has seen everything...
#  - Thank you for travising with Deutsche Builds
