[package]
name = "cursive-multiplex"
version = "0.3.2-alpha.0"
authors = ["Fin Christensen <christensen.fin@gmail.com>", "Johannes WÃ¼nsche <johannes.wuensche97@gmail.com>"]
edition = "2018"
description = "A tmux like multiplexer for gyscos/cursive views"
license = "BSD-3-Clause"
readme = "README.md"
keywords = ["cursive", "tui", "terminal", "tiling", "view"]
repository = "https://github.com/deinstapel/cursive-multiplex"
documentation = "https://docs.rs/cursive-multiplex"


[dependencies]
cursive_core = { version = "0.1.1", default-features = false }
cursive = { version = "0.15.0", default-features = false }
indextree = "4.0.0"
failure = "0.1.7"
failure_derive = "0.1.7"
log = "0.4.8"

[dev-dependencies]
serde_json = "1.0.48"
cursive_core = "0.1.1"

[badges]
travis-ci = { repository = "deinstapel/cursive-multiplex" }
is-it-maintained-open-issues = { repository = "deinstapel/cursive-multiplex" } 
